// SPDX-License-Identifier: GPL-2.0-only

pub fn mangle_mouse(subtype: u32) -> &'static str {
    match subtype {
        0 => "LeftButton",
        1 => "RightButton",
        2 => "MiddleButton",
        3 => "NoButton",
        4 => "LeftPressed",
        5 => "RightPressed",
        6 => "MiddlePressed",
        7 => "LeftReleased",
        8 => "RightReleased",
        9 => "MiddleReleased",
        10 => "MouseEnter",
        11 => "MouseLeave",
        16 => "Joystick1Left",
        17 => "Joystick1Right",
        18 => "Joystick1Up",
        19 => "Joystick1Down",
        21 => "Joystick1Button1",
        22 => "Joystick1Button2",
        23 => "Joystick1Button3",
        24 => "Joystick1Button4",
        25 => "Joystick1Button5",
        26 => "Joystick1Button6",
        27 => "Joystick1Button7",
        28 => "Joystick1Button8",
        31 => "Joystick2Left",
        32 => "Joystick2Right",
        33 => "Joystick2Up",
        34 => "Joystick2Down",
        36 => "Joystick2Button1",
        37 => "Joystick2Button2",
        38 => "Joystick2Button3",
        39 => "Joystick2Button4",
        40 => "Joystick2Button5",
        41 => "Joystick2Button6",
        42 => "Joystick2Button7",
        43 => "Joystick2Button8",
        50 => "GlobLeftButton",
        51 => "GlobRightButton",
        52 => "GlobMiddleButton",
        53 => "GlobLeftPressed",
        54 => "GlobRightPressed",
        55 => "GlobMiddlePressed",
        56 => "GlobLeftReleased",
        57 => "GlobRightReleased",
        58 => "GlobMiddleReleased",
        60 => "MouseWheelUp",
        61 => "MouseWheelDown",
        _ => crate::fail!("Invalid mouse subtype {subtype}"),
    }
}
