mypart1 = instance_create(x,y,obj_froghead)
mypart2 = instance_create(x,y,obj_froglegs)
hurtanim = 0
hurtsound = snd_ehurt1
talked = 0
whatiheard = -1
attacked = 0
killed = 0
global.heard = 0
takedamage = 0
mercymod=0
